services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false
  AppBundle\:
    exclude: '%kernel.project_dir%/src/AppBundle/{Entity,Repository,Resources,Tests}'
    resource: '%kernel.project_dir%/src/AppBundle/*'
  AppBundle\Controller\:
    resource: '%kernel.project_dir%/src/AppBundle/*'
    tags: ['controller.service_arguments']